sonar.projectKey=hub-ms-facturacion
sonar.projectName=hub-ms-facturacion
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src/tests
sonar.exclusions=src/tests/**
sonar.python.coverage.reportPaths=coverage.xml
